<?php

/**
 * @file
 * Processes various FullCalendar configuration extenders.
 */

/**
 * Implements hook_menu().
 */
function fullcalendar_options_menu() {
  $items = array();

  $items['admin/config/user-interface/fullcalendar/options'] = array(
    'title' => 'Options',
    'description' => 'Enable or disable extra FullCalendar options.',
    'page callback' => 'NOT_USED',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}
