<?php

/**
 * Implements hook_menu().
 */
function fullcalendar_colors_menu() {
  $items = array();

  $items['admin/config/calendar/fullcalendar/colors'] = array(
    'title' => 'Colors',
    'description' => 'Adjust FullCalendar color settings for entities.',
    'file' => 'fullcalendar_colors.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fullcalendar_admin_color_node_type_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  $items['admin/config/calendar/fullcalendar/colors/node'] = array(
    'title' => t('Node Type'),
    'file' => 'fullcalendar_colors.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fullcalendar_admin_color_node_type_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  if (module_exists('taxonomy')) {
    $items['admin/config/calendar/fullcalendar/colors/taxonomy'] = array(
      'title' => t('Taxonomy'),
      'file' => 'fullcalendar_colors.admin.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('fullcalendar_admin_color_taxonomy_settings'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'weight' => -8,
    );
  }

  $items['admin/config/calendar/fullcalendar/colors/user'] = array(
    'title' => t('User Role'),
    'file' => 'fullcalendar_colors.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fullcalendar_admin_color_user_role_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -6,
  );

  if (module_exists('og')) {
    $items['admin/config/calendar/fullcalendar/colors/og'] = array(
      'title' => t('Organic Groups'),
      'file' => 'fullcalendar_colors.admin.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('fullcalendar_admin_color_og_settings'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'weight' => -2,
    );
  }

  return $items;
}

/**
 * Implements hook_help().
 */
function fullcalendar_colors_help($path, $arg) {
  switch ($path) {
    case 'admin/help#fullcalendar_colors':
      return '<p>' . t('You can configure colors for your fullcalendar events based on taxonomy terms, node types, etc. on the <a href="@link">FullCalendar Colors administration page</a>.', array('@link' => '/admin/config/calendar/fullcalendar/colors')) . '</p>';
      break;
  }
}

/**
 * Implements hook_fullcalendar_classes().
 */
function fullcalendar_colors_fullcalendar_classes($entity) {
  require_once './' . drupal_get_path('module', 'fullcalendar_colors') . '/fullcalendar_colors.inc';
  $classes = array();
  $css = '';

  $hook = 'fullcalendar_colors_create_css';
  foreach (module_implements($hook) as $module) {
    $function = $module . '_' . $hook;
    $function($classes, $css, $entity);
  }

  // Inject created css string.
  drupal_add_css($css, 'inline');

  return $classes;
}

/**
 * Builds a css string.
 *
 * @param $css
 *   Array containing css.
 * @param $class
 *   Classname used for the new css selectors.
 * @param $color
 *   The new background color.
 */
function _fullcalendar_colors_build_css_string(&$css, $class, $color) {
  $css .= ' .' . $class . ',';
  $css .= ' .' . $class . ' .fc-event-skin,';
  $css .= ' .' . $class . ' .fc-event-time,';
  $css .= ' .' . $class . ' a';
  $css .= '{background-color: ' . $color . '; border-color: ' . $color . ';}';
}
